// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo0GWEhlmQoIcbpkYex4vKubybnpNt7a8',
    appId: '1:512876275064:android:332858b7d8b64542c6d48d',
    messagingSenderId: '512876275064',
    projectId: 'flutter-project-595e7',
    databaseURL: 'https://flutter-project-595e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-595e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3UJfWH4xDLXWEeTBIa4y2PJUnSUlkFlE',
    appId: '1:512876275064:ios:b86466128d708613c6d48d',
    messagingSenderId: '512876275064',
    projectId: 'flutter-project-595e7',
    databaseURL: 'https://flutter-project-595e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-595e7.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyErU04o-GwiblPtFeOCx1GSxWHo2P2MU',
    appId: '1:512876275064:web:d5e46b052d949d52c6d48d',
    messagingSenderId: '512876275064',
    projectId: 'flutter-project-595e7',
    authDomain: 'flutter-project-595e7.firebaseapp.com',
    databaseURL: 'https://flutter-project-595e7-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-595e7.firebasestorage.app',
    measurementId: 'G-GW0Z2FH4XQ',
  );

}